{
 "title": "MineLib",
 "tags": [
  "minelib",
  "nats"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (app, uuid) (application_process_cpu_usage)"
    },
    {
     "expr": " sum by (app, uuid) (application_process_private_memory_size)"
    },
    {
     "expr": "sum by (app, uuid) (application_total_exception_count)"
    },
    {
     "expr": " sum by (app, uuid) (time() - application_start_time_seconds)"
    }
   ]
  },
  {
   "title": "Classic Players",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "application_players_connected__classic_protocols_"
    }
   ]
  },
  {
   "title": "Netty Players",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "application_players_connected__netty_protocols_"
    }
   ]
  },
  {
   "title": "Pocket Players",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "application_players_connected__pocket_protocols_"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "application_process_private_memory_size",
     "legendFormat": "{{uuid}} {{app}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "application_process_cpu_usage", "legendFormat": "{{uuid}} {{app}}" }
   ]
  }
 ]
}