version: '3.7'

networks:
  website:

services:
#Network Bus
  nats:
    image: nats
    restart: always
    container_name: nats_website
    command:
      - '--cluster=nats://0.0.0.0:6222'
      - '--routes=nats://nats.aragas.org:46222' 
    volumes:
      - ./nats/nats-server.conf:/opt/bitnami/nats/nats-server.conf
    ports:
      - 6222:6222
    expose:
      - 4222
    networks:
      - website
      
#WebSite
  minelib.server.website:
    image: ${DOCKER_REGISTRY-}minelib_server_website
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      - nats
    build:
      context: ../..
      dockerfile: MineLib/Executables/MineLib.Server.WebSite/Dockerfile
    ports:
      - 5280:80
    networks:
      - website
      
#  minelib.server.website.nginx:
#    image: nginx:alpine
#    depends_on:
#      - minelib.server.website
#    volumes:
#      - ./nginx_website/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx_website/logs:/var/log/nginx
#    ports:
#      - 12080:80
#      - 12443:443
#    networks:
#      - website