version: '3.7'

services:
  minelib.server.website:
    image: ${DOCKER_REGISTRY-}minelib_server_website
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    build:
      context: ../..
      dockerfile: MineLib/Executables/MineLib.Server.WebSite/Dockerfile
    ports:
      - 5280:80