version: '3.7'

networks:
  services:

services:
#Network Bus
  nats:
    image: nats
    restart: always
    container_name: nats_services
    command:
      - '--cluster=nats://0.0.0.0:6222'
      - '--routes=nats://nats.aragas.org:46222' 
    volumes:
      - ./nats/nats-server.conf:/opt/bitnami/nats/nats-server.conf
    ports:
      - 6222:6222
    expose:
      - 4222
    networks:
      - services

#Server
  minelib.server.entitybus:
    image: ${DOCKER_REGISTRY-}minelib_server_entitybus
    restart: always
    depends_on:
      - nats
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.EntityBus/Dockerfile
    networks:
      - services
  minelib.server.playerbus:
    image: ${DOCKER_REGISTRY-}minelib_server_playerbus
    restart: always
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.PlayerBus/Dockerfile
    depends_on:
      - nats
    networks:
      - services
  minelib.server.worldbus:
    image: ${DOCKER_REGISTRY-}minelib_server_worldbus
    restart: always
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.WorldBus/Dockerfile
    depends_on:
      - nats
    networks:
      - services