version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}
  postgresql_data: {}

networks:
  prometheus:
  internal:
  website:
  server:
  grafana:

services:
#Network Bus
  nats:
    image: nats
    command:
      - '--cluster=nats://0.0.0.0:6222'
      - '--routes=nats://nats.aragas.org:46222' 
    volumes:
      - ./nats/nats-server.conf:/opt/bitnami/nats/nats-server.conf
    ports:
      - 6222:6222
    expose:
      - 4222
    networks:
      - internal
      - website

#WebSite
  minelib.server.website:
    image: ${DOCKER_REGISTRY-}minelib_server_website
    depends_on:
      - nats
    build:
      context: ../..
      dockerfile: MineLib/Executables/MineLib.Server.WebSite/Dockerfile
      - 12080:80
      - 12443:443
    networks:
      - website


#Server
  minelib.server.entitybus:
    image: ${DOCKER_REGISTRY-}minelib_server_entitybus
    depends_on:
      - nats
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.EntityBus/Dockerfile
    networks:
      - internal
  minelib.server.playerbus:
    image: ${DOCKER_REGISTRY-}minelib_server_playerbus
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.PlayerBus/Dockerfile
    depends_on:
      - nats
    networks:
      - internal
  minelib.server.worldbus:
    image: ${DOCKER_REGISTRY-}minelib_server_worldbus
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.WorldBus/Dockerfile
    depends_on:
      - nats
    networks:
      - internal

  minelib.server.proxy:
    image: ${DOCKER_REGISTRY-}minelib_server_proxy
    build:
      context: ../..
      dockerfile: MineLib/Executables/MineLib.Server.Proxy/Dockerfile
    depends_on:
      - minelib.server.entitybus
      - minelib.server.playerbus
      - minelib.server.worldbus
      - minelib.server.website
    ports:
      - 25565:25565
      - 56552:56552
    networks:
      - internal
      - website
      - server