version: '3.4'

services:
  aragas.db:
    image: postgres
    #restart: always
    environment:
     POSTGRES_DB: minelib
     POSTGRES_USER: minelib
     POSTGRES_PASSWORD: minelib

  aragas.nats:
    image: 'nats-streaming:latest'
    #restart: always
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    #volumes:
    #  - /path/to/nats-server.conf:/opt/bitnami/nats/nats-server.conf

  minelib.server.entitybus:
    image: ${DOCKER_REGISTRY-}minelibserverentitybus
    #restart: always
    depends_on:
      - aragas.db
      - aragas.nats
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.EntityBus/Dockerfile
  minelib.server.playerbus:
    image: ${DOCKER_REGISTRY-}minelibserverplayerbus
    #restart: always
    depends_on:
      - aragas.db
      - aragas.nats
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.PlayerBus/Dockerfile
  minelib.server.worldbus:
    image: ${DOCKER_REGISTRY-}minelibserverworldbus
    #restart: always
    depends_on:
      - aragas.db
      - aragas.nats
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.WorldBus/Dockerfile

  minelib.server.proxy:
    image: ${DOCKER_REGISTRY-}minelibserverproxy
    #restart: always
    depends_on:
      - aragas.nats
      - minelib.server.entitybus
      - minelib.server.playerbus
      - minelib.server.worldbus
    ports:
      - "25565:25565"
    build:
      context: ../..
      dockerfile: MineLib/Executables/MineLib.Server.Proxy/Dockerfile