version: '3.4'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
#    networks:
#      - back-tier
#    restart: always

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
#    networks:
#      - back-tier
#      - front-tier
#    restart: always

  aragas.db:
    image: postgres
    #restart: always
    environment:
     POSTGRES_DB: minelib
     POSTGRES_USER: minelib
     POSTGRES_PASSWORD: minelib

  aragas.nats:
    image: 'nats-streaming:latest'
    #restart: always
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    #volumes:
    #  - /path/to/nats-server.conf:/opt/bitnami/nats/nats-server.conf


  aragas.qserver.nats.metrics:
    image: ${DOCKER_REGISTRY-}aragasqservernatsmetrics
    #restart: always
    build:
      context: ../..
      dockerfile: Aragas.QServer.NATS.Metrics/Dockerfile
    ports:
      - "9000:80"

  minelib.server.entitybus:
    image: ${DOCKER_REGISTRY-}minelibserverentitybus
    #restart: always
    depends_on:
      - aragas.db
      - aragas.nats
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.EntityBus/Dockerfile
  minelib.server.playerbus:
    image: ${DOCKER_REGISTRY-}minelibserverplayerbus
    #restart: always
    depends_on:
      - aragas.db
      - aragas.nats
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.PlayerBus/Dockerfile
    deploy:
      mode: replicated
      replicas: 6
  minelib.server.worldbus:
    image: ${DOCKER_REGISTRY-}minelibserverworldbus
    #restart: always
    depends_on:
      - aragas.db
      - aragas.nats
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.WorldBus/Dockerfile

  minelib.server.proxy:
    image: ${DOCKER_REGISTRY-}minelibserverproxy
    #restart: always
    depends_on:
      - aragas.nats
      - minelib.server.entitybus
      - minelib.server.playerbus
      - minelib.server.worldbus
    ports:
      - "25565:25565"
    build:
      context: ../..
      dockerfile: MineLib/Executables/MineLib.Server.Proxy/Dockerfile