version: '3.7'

services:
#WebSite
  minelib.server.website:
    image: ${DOCKER_REGISTRY-}minelib_server_website
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ../..
      dockerfile: MineLib/Executables/MineLib.Server.WebSite/Dockerfile
    ports:
      - 12080:80
      - 12443:443