version: '3.7'

services:
#Server
  minelib.server.entitybus:
    image: ${DOCKER_REGISTRY-}minelib_server_entitybus
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.EntityBus/Dockerfile

  minelib.server.playerbus:
    image: ${DOCKER_REGISTRY-}minelib_server_playerbus
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.PlayerBus/Dockerfile

  minelib.server.worldbus:
    image: ${DOCKER_REGISTRY-}minelib_server_worldbus
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    build:
      context: ../..
      dockerfile: MineLib/Executables/Bus/MineLib.Server.WorldBus/Dockerfile